### ISSUE TITLE
Big Issue

### ISSUE THREAD

**Issue by developer9998** [zaynethedev/Index#5]
this sucks
![devroseagain](https://github.com/user-attachments/assets/59763770-9280-4711-a6ac-083111193cf2)
:3

**Comment by NgbatzYT** [comment]
i hope you stub you toe really hard on the corner of a pole

**Comment by ciperuoy** [comment]
ahh alright, thanks for the feedback dev9998.

**Comment by NgbatzYT** [comment]
i think your talking about grate which is a bark clone. just maybe

**Comment by Br0des** [comment]
> this sucks ![devroseagain](https://private-user-images.githubusercontent.com/81720436/398922490-59763770-9280-4711-a6ac-083111193cf2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU4MzcwNTIsIm5iZiI6MTczNTgzNjc1MiwicGF0aCI6Ii84MTcyMDQzNi8zOTg5MjI0OTAtNTk3NjM3NzAtOTI4MC00NzExLWE2YWMtMDgzMTExMTkzY2YyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTAyVDE2NTIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1ODgzMTVkZDhiYTk5OGJhZGU3YTU5OTdjZmE1MTE2N2MyOWEwNzc5MDQ0YTk0YmVjMWE3MzJmOGYyZDRiZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.F31Tu9lNZJoUCoo6onDQQs0kdNYQ1CSC4pwRkyU1PnM) :3

real

**Comment by XenonOrSomething** [comment]
this is a true pull request

**Comment by XenonOrSomething** [comment]
100% factual
